### ISSUE TITLE
Optional Google Api Key

### ISSUE THREAD

**Issue by drobison** [sethwebster/GoogleMaps.LocationServices#10]
It would be useful if the location services class constructors took in an optional google api key.  If present this would be used when making request.

**Comment by sethwebster** [comment]
Great suggestion. A PR would be welcome.

**Comment by kaiokassiano** [comment]
The user @adrotter made a PR with the required modifications. https://github.com/sethwebster/GoogleMaps.LocationServices/pull/12

**Comment by matthewjonesvsp** [comment]
Do I need an API key for lets say lets than 2,500 requests a day?

**Comment by adrotter** [comment]
No, you get a cap of 2500 a day without a key.  Only with a key can you go
above 2500 a day.  After that every 10 requests is 1 cent

**Comment by matthewjonesvsp** [comment]
Great, thank you for replying. I am really new to the process of API's etc. So in your opinion, which I am guessing you are way more knowledgeable than me in the mater, could I write a commercial application using this service without purchasing or needing an API key? 

I apologize if that question is too broad. Thanks for your help!
