### ISSUE TITLE
Geolocation Precision

### ISSUE THREAD

**Issue by Sandi89** [sethwebster/GoogleMaps.LocationServices#11]
Hi, 

Thank you for creating this library. It works great for me. Is there a way to increase geolocation precision? I only get 7 decimal points no matter how well I specify the address...

**Comment by sethwebster** [comment]
I believe it's the direct result from Google passed on, but will get back to you.

**Comment by yb11206** [comment]
@sethwebster  is this issue resolved ?

**Comment by sethwebster** [comment]
No -- this is the result from google.
