### ISSUE TITLE
Wrong request for GetAddressFromLatLang method

### ISSUE THREAD

**Issue by dimdar74** [sethwebster/GoogleMaps.LocationServices#15]
Hi,

When I use GetAddressFromLatLang the the coordinate are not formatted correctly because use my culture
(italian) where decimal point is comma so the requested url is:

https://maps.googleapis.com/maps/api/geocode/xml?latlng=43,9361097,10,9106845&sensor=false

instead of

https://maps.googleapis.com/maps/api/geocode/xml?latlng=43.9361097,10.9106845&sensor=false

**Comment by fbischoff77** [comment]
Hi dimdar74, have you solved your problem ?

**Comment by dimdar74** [comment]
Hi, fbischoff77


Yes, i have downloaded source code and i have correct it

________________________________
Da: fbischoff77 <notifications@github.com>
Inviato: lunedì 24 luglio 2017 17:14
A: sethwebster/GoogleMaps.LocationServices
Cc: dimdar74; Author
Oggetto: Re: [sethwebster/GoogleMaps.LocationServices] Wrong request for GetAddressFromLatLang method (#15)


Hi dimdar74, have you solved your problem ?

**Comment by sethwebster** [comment]
Did you want to submit a PR?

**Comment by a-a-k** [comment]
@sethwebster please, take a look to my PR as soon as possible and if it's ok we are waiting for NuGet updates.

**Comment by alexandra142** [comment]
The same here
