### ISSUE TITLE
Would I need an API key?

### ISSUE THREAD

**Issue by matthewjonesvsp** [sethwebster/GoogleMaps.LocationServices#17]
I am currently writing an application to go commercial (hopefully). This framework is awesome and I am curious, I see where there has been an API key implementation, however I am wondering if it would be necessary?

For now, all I am doing is dropping Lat/Long and requesting Address or dropping address and requesting Lat/Long. Just would like to hear your thoughts? From my understanding and from what I have researched, an API key is not need?

Respectfully,

**Comment by sethwebster** [comment]
I haven't made an API a requirement.


Seth Webster
@sethwebster <http://twitter.com/sethwebster> | web site
<http://sethwebster.com/> | photography <http://photos.sethwebster.com/> |
IMDB <http://www.imdb.com/name/nm0917003/?ref_=fn_al_nm_1> | +1.646.350.0739
(c)

**Comment by sethwebster** [comment]
@matthewjonesvsp  -- apiKey isn't _required_ but lookups are very limited without (in terms of rate).
