### ISSUE TITLE
Anyone using this in a commercial application?

### ISSUE THREAD

**Issue by matthewjonesvsp** [sethwebster/GoogleMaps.LocationServices#18]
This might be the wrong place to ask this, but I am new to GitHub and would just like to see if anyone has used this framework in a commercial application. It is working flawlessly for me at the moment... writing in Vb.Net

**Comment by sethwebster** [comment]
I'm sure it has.

**Comment by matthewjonesvsp** [comment]
Yeah, that was a dumb question... what would be the proper way of inserting an API for VB.Net?
