### ISSUE TITLE
Request Not Authorized or Over QueryLimit

### ISSUE THREAD

**Issue by amfh** [sethwebster/GoogleMaps.LocationServices#22]
Hi
I am getting exception on "Request Not Authorized or Over QueryLimit" when running a test console app with my own google api key. Please i need help to figure out this issue.
![image](https://user-images.githubusercontent.com/10772909/36252546-40ad2c2c-1245-11e8-8857-3c51619d68ce.png)

![image](https://user-images.githubusercontent.com/10772909/36252600-7573e518-1245-11e8-9720-2ea7730377b4.png)

Thanks

**Comment by sethwebster** [comment]
I think that method doesn't (in the library) pass the ApiKey. I have it fixed in the code here, but have not been able to get a new Nuget package release built. I believe if you clone from code, and build yourself, it should be fixed.

**Comment by segibambo** [comment]
Thanks, Seth. I was able to build and add as a reference to my project. Works like a charm!

**Comment by Vijayapriyacs** [comment]
How to solve this issue
 var address = "Stavanger, Norway"; //Use textbox value textbox1.text

            var locationService = new GoogleLocationService();
            var point = locationService.GetLatLongFromAddress(address);
I got same error while I run above code

**Comment by segibambo** [comment]
> How to solve this issue
> var address = "Stavanger, Norway"; //Use textbox value textbox1.text
> 
> ```
>         var locationService = new GoogleLocationService();
>         var point = locationService.GetLatLongFromAddress(address);
> ```
> I got same error while I run above code

You need to Get your own API Key from Google Location Services, then pass it as a constructor parameter to new GoogleLocationService("Key"). 

The default key always runs into that issue, I guess due to high traffic on that key vis-a-vis library integration to live apps.

**Comment by sethwebster** [comment]
Closing as resolved.

**Comment by benyusouf** [comment]
I'm currently getting this error even though I'm passing my own API key, please how do I fix it?
