### ISSUE TITLE
GetLatLongFromAddress gives different coordinates via code

### ISSUE THREAD

**Issue by amfh** [sethwebster/GoogleMaps.LocationServices#23]
Hi
Thank you for this simple and fantastic package. I am wondering why GetLatLongFromAddress(address) gives different lat and longs for such a request on address "1412 , Norway" via the code. If i run the request URL via an browser then it returns correct coordinates. What i am doing wrong?

CODE VS BROWSER:

 
![geocoordinates in code vs browser](https://user-images.githubusercontent.com/10772909/37705747-5822e428-2cfd-11e8-916a-d0dfa7c3f2c3.png)

Following is the response in xml that is returned running the code:
{<GeocodeResponse>
  <status>OK</status>
  <result>
    <type>country</type>
    <type>political</type>
    <formatted_address>Norway</formatted_address>
    <address_component>
      <long_name>Norway</long_name>
      <short_name>NO</short_name>
      <type>country</type>
      <type>political</type>
    </address_component>
    <geometry>
      <location>
        <lat>60.4720240</lat>
        <lng>8.4689460</lng>
      </location>
      <location_type>APPROXIMATE</location_type>
      <viewport>
        <southwest>
          <lat>57.8097000</lat>
          <lng>4.0649000</lng>
        </southwest>
        <northeast>
          <lat>71.3078000</lat>
          <lng>31.3549999</lng>
        </northeast>
      </viewport>
      <bounds>
        <southwest>
          <lat>57.8097000</lat>
          <lng>4.0649000</lng>
        </southwest>
        <northeast>
          <lat>71.3078000</lat>
          <lng>31.3549999</lng>
        </northeast>
      </bounds>
    </geometry>
    <place_id>ChIJv-VNj0VoEkYRK9BkuJ07sKE</place_id>
  </result>
</GeocodeResponse>}

**Comment by gillianomenezes** [comment]
Same issue here. Works fine in every direction on my app, except one.

**Comment by sethwebster** [comment]
I tried to reproduce and was unable.
