### ISSUE TITLE
GetAddressFromLatLong Bad Request

### ISSUE THREAD

**Issue by hansgunnar** [sethwebster/GoogleMaps.LocationServices#24]
Hi, I am trying to use Location services to resolve lat long coordinates into an address but when I am trying to use that method I get a 400 Bad Request, any idea Why?

**Comment by sethwebster** [comment]
A code sample or other information would be helpful.

**Comment by hansgunnar** [comment]
Hi, I'm just using it like this:
```
var locationService = new GoogleLocationService();
  
                            var locationAddress = locationService.GetAddressFromLatLang(tripMessage.Latitude, tripMessage.Longitude);
                            location = locationAddress.Address;
```

The latitude and longitude values are of type double.
Got a try catch around that.
There shouldn't be any more to it, should it?

Thanks

**Comment by sethwebster** [comment]
You probably need to set an API KEY (see docs) as without it, you're probably getting refused. Without more info, I can't help you.

**Comment by marcdion** [comment]
Even when passing an API key, the function public GetAddressFromLatLang does not pass the API key to the request: 

`xmlDocument.Load(string.Format(this.APIUrlRegionFromLatLong, (object) latitude, (object) longitude));`

For example, in the GetLatLongFromAddress function, the API key is appended at the end of the request before it is sent: 

`      XDocument xdocument = XDocument.Load(string.Format(this.APIUrlLatLongFromAddress, (object) Uri.EscapeDataString(address)) + "&key=" + this.APIKey);
`
