### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by mikecsom** [sethwebster/GoogleMaps.LocationServices#25]
I am getting a System.Net.WebException: 'The remote server returned an error: (500) Internal Server Error.' only when I search for Oklahoma City OK.  Any ideas?

Here is my code:

var gls = new GoogleLocationService("API_KEY");
MapPoint mp = gls.GetLatLongFromAddress("Oklahoma City, OK, USA");

Thanks in advance,

Mike

**Comment by sethwebster** [comment]
Are you setting an actual API_KEY?
