### ISSUE TITLE
Additional Functionality - GetDirections using Latitude and Longitude

### ISSUE THREAD

**Issue by RodPerrott** [sethwebster/GoogleMaps.LocationServices#26]
My project required a directions lookup using Latitude and Longitudes.

Based on your source code I have tested the code attached and it seems to work well.

Would be appreciated if you could consider this new functionality in the future.

[DirectionsLatLon.txt](https://github.com/sethwebster/GoogleMaps.LocationServices/files/2007056/DirectionsLatLon.txt)

**Comment by sethwebster** [comment]
Would you be willing, @RodPerrot, to submit this instead as a pull request?

**Comment by sethwebster** [comment]
Closing now since no PR submitted.
