### ISSUE TITLE
Error when trying to add this package on Xamarin.Forms 3 with Netstandard 2.0 and Android 8.1

### ISSUE THREAD

**Issue by olivertech** [sethwebster/GoogleMaps.LocationServices#28]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package GoogleMaps.LocationServices 1.2.0.1 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package GoogleMaps.LocationServices 1.2.0.1 supports: net40 (.NETFramework,Version=v4.0)

**Comment by sethwebster** [comment]
I just pushed a new version, @olivertech. Not sure if it will help as it's dotnetcore2.1 but see if it helps. You can also download the source and self-build, perhaps.

**Comment by sethwebster** [comment]
Can you try this now 🤕 ?
