### ISSUE TITLE
Latest on Nuget is 1.2.0.1 < current

### ISSUE THREAD

**Issue by 23min** [sethwebster/GoogleMaps.LocationServices#29]
I would like to resolve Issue #15 (decimal separator causes HTTP 400)

When will the Nuget package be updated?

**Comment by sethwebster** [comment]
Hey, @23min - I just was able to send this up. I had to port it to DotNet core since I am no longer using Windows at all.

Can you try this and see if it works on windows?

**Comment by mhwlng** [comment]
Could not install package 'GoogleMaps.LocationServices 1.2.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by sethwebster** [comment]
@mhwlng I don't have the ability current to build this for that framework version. Feel free to download the code and target it for yourself. Shouldn't require much fixing ... you could also use an earlier version in history where it was 4.7.1 compatible.

Apologies.
