### ISSUE TITLE
Help Wanted: Build with Multi-Targeting

### ISSUE THREAD

**Issue by sethwebster** [sethwebster/GoogleMaps.LocationServices#32]
I no longer use Windows and can't build a version for net461 or other windows-specific targets.

I've build this for net standard 2.1 but need help with getting multi-targeting working.

Anyone available to help?

**Comment by fluffynuts** [comment]
I can help with this -- have done this for a few of my packages in https://github.com/fluffynuts/peanutbutter, eg https://www.nuget.org/packages/PeanutButter.Utils/; the difficulty is that I assume you'd like to multi-target your nuget packages -- which means you'd need a windows machine (or vm) to build them using multi-targeted csproj files. Do you have a windows machine/vm available? Would you be looking for someone to build packages too?

**Comment by sethwebster** [comment]
I'd need someone to build packages too :\

Thanks for offering to help :)

**Comment by iliDaedalus** [comment]
1year and 3months later..
Do you guys have any news/update?

**Comment by fluffynuts** [comment]
Eh, I kinda forgot about this... I can also (probably) build packages -- the fun is going to be in distributing the package.

However, before anyone even goes down that road: I've had quite a reasonable bit of success with a props file which can direct msbuild to find .net framework from a local install of Mono. It works for [NExpect](https://github.com/fluffynuts/NExpect), and _mostly_ for [PeanutButter](https://github.com/fluffynuts/PeanutButter), where the outliers in the latter are incredibly windows-specific. I can't take credit for this -- I found it somewhere online (forget where). I don't know what OS you're working on, but the original post mentioned working with OSX, and this definitely works with Gentoo Linux.

[mono-targets.zip](https://github.com/sethwebster/GoogleMaps.LocationServices/files/4259434/mono-targets.zip)

You can use by unpacking and adding something like:
```xml
<Import Project="MonoForFramework.targets"/>
```
to the affected project. Don't forget to update your csproj with something like
```xml
<TargetFrameworks>net452;net462;netstandard2.0</TargetFrameworks>
```
as well -- of course, selecting the frameworks you'd like to target (:

**Comment by sethwebster** [comment]
MacOS... I'll see what I can do some time soon.

**Comment by sethwebster** [comment]
@iliDaedalus - I assume you've moved on but yeah, it's targeted at dotnet standard now so should work everywhere. So sorry for the delay. Wasn't on Windows for a long time.
