### ISSUE TITLE
GetAddressFromLatLang() returns empty AddressData object

### ISSUE THREAD

**Issue by aldrichdev** [sethwebster/GoogleMaps.LocationServices#33]
Hello. I am using the Google Location Service API like this:

            var locationService = new GoogleLocationService(MyGoogleMapsApiKey);
            var addressData = locationService.GetAddressFromLatLang(latLong.Latitude, latLong.Longitude);

My latitude and longitude are being pulled in correctly. However when the second line runs, the addressData object is completely empty. It's weird because when I try hitting the URL it works fine:

https://maps.googleapis.com/maps/api/geocode/xml?latlng=43.0389025,-87.9064736&sensor=false&key=[myprivatekey]

While I could just use the URL in my code and emulate what you have in Git, that seems like a bad idea if you ever change your XML, then I'd have to update my code every time, etc. Thanks.

**Comment by HassanMoin** [comment]
Also getting the same issue.
Another thing to add is that after calling GetAddressFromLatLang() for a few times after I got empty results starts throwing **403 forbidden error** instead of returning empty result.

**Comment by sethwebster** [comment]
@HassanMoin Are you using your own API key?

**Comment by sethwebster** [comment]
@aldrichdev - I just ran a similar test with the code and it's working fine. Which version are  you using? Do you have an actual repo I could look at with relevant code?

**Comment by HassanMoin** [comment]
@sethwebster. Yes. The Google api is working perfect for other methods. For example get Getlatlongfromaddress. The issue come's in GetAddressFromLatLang....sometimes it returns empty object and sometimes 403 forbidden exception.

**Comment by sethwebster** [comment]
@HassanMoin -- As long as the api key is presented and the calls are not passing something that Google's api can't understand, it should work. This library is pretty simple; a wrapper around a web request ... Feel free to poke around the code and see if you can find something ... Perhaps passing the api key somewhere isn't happening?

**Comment by aldrichdev** [comment]
Hi @sethwebster - apologies for the delay on this reply - totally forgot. I am using GoogleMaps.LocationServices version 0.1.6329.16944, according to Visual Studio. However packages.config reports that it is version 1.2.0.1, so not sure... one of those.

I don't have a repo you can access to test but I will see if I can replicate this in a new solution and then put it on GitHub publicly.

Thanks,
Paul

**Comment by wasimjee** [comment]
having same issue 403 forbidden error

**Comment by sethwebster** [comment]
@wasimjee - is there a repo I can see? Make sure you are passing your personal API_KEY.

**Comment by marcdion** [comment]
Also having the same issue using 1.2.0.1.. The GetAddressFromLatLang does not seem to be passing the API key in the request:

`  xmlDocument.Load(string.Format(this.APIUrlRegionFromLatLong, (object) latitude, (object) longitude));`

Where as in GetLatLongFromAddress, the API key is passed:

`XDocument xdocument = XDocument.Load(string.Format(this.APIUrlLatLongFromAddress, (object) Uri.EscapeDataString(address)) + "&key=" + this.APIKey);`
