### ISSUE TITLE
NuGet Error!

### ISSUE THREAD

**Issue by digitxo** [sethwebster/GoogleMaps.LocationServices#34]
```
Install-Package : Could not install package 'GoogleMaps.LocationServices 1.2.0.2'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package GoogleMaps.LocationServices
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by sethwebster** [comment]
See #32

**Comment by matmiranda** [comment]
I have the same problem:

> Severity Code Description Project File Line Suppression State
> Error The package 'GoogleMaps.LocationServices 1.2.0.2' could not be installed. You are trying to install this package in a project that is intended for '.NETFramework, Version = v4.7', but the package does not contain any assembly or content reference that is compatible with this framework. For more information, please contact the package author.

**Comment by matmiranda** [comment]
@sethwebster  This problem should not be closed, reopen now !!!
