### ISSUE TITLE
Unable to Install through NuGet

### ISSUE THREAD

**Issue by wasimjee** [sethwebster/GoogleMaps.LocationServices#35]
Could not install package 'GoogleMaps.LocationServices 1.2.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by larrybud2004** [comment]
Looks like 1.2.0.2 is having that problem.  I get the same with .net version 4.6.1

I did not havc a problem installing 1.2.0.1 however. Looks like they broke something.
