### ISSUE TITLE
Request denied, it's likely you need to enable the necessary Google maps APIs Error

### ISSUE THREAD

**Issue by benyusouf** [sethwebster/GoogleMaps.LocationServices#39]
Hi Sethwebster,

I recentky update the Nuget package for this repository and I'm getting this error every time I send a request to the Geocoding API. I go through the code and have seen that the error is thrown whenever Google API return "Request denied". I have enabled Geocoding API as part of my project, in fact, I have enabled all Google Map related APIs but I'm still getting this error.

Could this possibly be "Query Limit error"? Please help

**Comment by hbopuri** [comment]
I had same problem I enabled Geocoding API and that worked.

**Comment by sethwebster** [comment]
> I had same problem I enabled Geocoding API and that worked.

Correct, you must enable the API first with Google APIs.
